/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import model.User;

/**
 *
 * @author alehenz
 */
public class RegistrationJPanel extends javax.swing.JPanel {
    
    private ViewJPanel viewPanel;
    private javax.swing.JPanel cardContainer;
    /**
     * Creates new form RegistrationJPanel
     */
    public RegistrationJPanel() {
        initComponents();
        genderCombo.setSelectedIndex(-1);
        continentCombo.setSelectedIndex(-1);
    }
    
    public void setViewPanel(ViewJPanel viewPanel) {
        this.viewPanel = viewPanel;
    }

    public void setCardContainer(javax.swing.JPanel cardContainer) {
        this.cardContainer = cardContainer;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        hobbiesTextArea = new javax.swing.JTextArea();
        lastNameTextField = new javax.swing.JTextField();
        genderCombo = new javax.swing.JComboBox<>();
        experienceLabel1 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JFormattedTextField(createPhoneMask());
        continentCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        experienceTextArea = new javax.swing.JTextArea();
        photoTextField = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        asterisk1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        asterisk2 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        asterisk3 = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        asterisk4 = new javax.swing.JLabel();
        asterisk5 = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        asterisk6 = new javax.swing.JLabel();
        continentLabel = new javax.swing.JLabel();
        asterisk7 = new javax.swing.JLabel();
        experienceLabel = new javax.swing.JLabel();
        asterisk9 = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        requiredFieldLabel = new javax.swing.JLabel();
        jCalendarCombo = new de.wannawork.jcalendar.JCalendarComboBox();
        ageLabel1 = new javax.swing.JLabel();
        asterisk8 = new javax.swing.JLabel();
        asterisk11 = new javax.swing.JLabel();

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        hobbiesTextArea.setColumns(20);
        hobbiesTextArea.setRows(5);
        jScrollPane2.setViewportView(hobbiesTextArea);

        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboActionPerformed(evt);
            }
        });

        experienceLabel1.setText("Hobbies:");

        phoneTextField.setToolTipText("");

        continentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Asia", "Central America & Caribbean", "Europe", "North America", "Oceania", "South America" }));
        continentCombo.setToolTipText("");
        continentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continentComboActionPerformed(evt);
            }
        });

        experienceTextArea.setColumns(20);
        experienceTextArea.setRows(5);
        jScrollPane1.setViewportView(experienceTextArea);

        photoTextField.setColumns(16);
        photoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoTextFieldActionPerformed(evt);
            }
        });

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        emailLabel.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        asterisk1.setForeground(new java.awt.Color(204, 0, 51));
        asterisk1.setText("*");

        firstNameLabel.setText("First Name:");

        asterisk2.setForeground(new java.awt.Color(204, 0, 51));
        asterisk2.setText("*");

        lastNameLabel.setText("Last Name:");

        asterisk3.setForeground(new java.awt.Color(204, 0, 51));
        asterisk3.setText("*");

        genderLabel.setText("Gender:");

        asterisk4.setForeground(new java.awt.Color(204, 0, 51));
        asterisk4.setText("*");

        asterisk5.setForeground(new java.awt.Color(204, 0, 51));
        asterisk5.setText("*");

        phoneLabel.setText("Phone Number:");

        asterisk6.setForeground(new java.awt.Color(204, 0, 51));
        asterisk6.setText("*");

        continentLabel.setText("Continent:");

        asterisk7.setForeground(new java.awt.Color(204, 0, 51));
        asterisk7.setText("*");

        experienceLabel.setText("Experience:");

        asterisk9.setForeground(new java.awt.Color(204, 0, 51));
        asterisk9.setText("*");

        photoLabel.setText("Photo:");

        requiredFieldLabel.setText("indicates required field");

        jCalendarCombo.setToolTipText("");

        ageLabel1.setText("Date of Birth:");

        asterisk8.setForeground(new java.awt.Color(204, 0, 51));
        asterisk8.setText("*");

        asterisk11.setForeground(new java.awt.Color(204, 0, 51));
        asterisk11.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asterisk8)
                            .addComponent(asterisk11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experienceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(experienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(photoTextField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(uploadButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asterisk6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asterisk5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asterisk7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(continentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(continentCombo, 0, 270, Short.MAX_VALUE)
                                .addComponent(emailTextField))
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asterisk9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requiredFieldLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asterisk4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asterisk1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(asterisk2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(asterisk3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(lastNameTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCalendarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisk1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asterisk2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel)
                    .addComponent(asterisk3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel1)
                            .addComponent(asterisk4))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCalendarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experienceLabel)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoneLabel)
                                    .addComponent(asterisk5))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel)
                            .addComponent(asterisk6))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(continentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(continentLabel)
                            .addComponent(asterisk7))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(experienceLabel1)
                            .addComponent(asterisk11))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadButton)
                    .addComponent(photoLabel)
                    .addComponent(asterisk8))
                .addGap(10, 10, 10)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requiredFieldLabel)
                    .addComponent(asterisk9))
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void genderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboActionPerformed

    private void continentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continentComboActionPerformed

    private void photoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoTextFieldActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            photoTextField.setText(selectedFile.getAbsolutePath());

            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = icon.getImage().getScaledInstance(uploadButton.getWidth(), uploadButton.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledImage);

            uploadButton.setIcon(icon);
            uploadButton.setText("");
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

        String errorTitle = "Oops... Input Error";

        try {
            String firstName = firstNameTextField.getText();
            String lastName = lastNameTextField.getText();
            LocalDate dateOfBirth = jCalendarCombo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int age = (int) Period.between(jCalendarCombo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), LocalDate.now()).getYears();
            String gender = (String) genderCombo.getSelectedItem();
            String phone = phoneTextField.getText();
            String email = emailTextField.getText();
            String continent = (String) continentCombo.getSelectedItem();
            String experience = experienceTextArea.getText();
            String hobbies = hobbiesTextArea.getText();
            String photoPath = photoTextField.getText();

            //Validate first name
            if (firstName == null || firstName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please provide your first name", errorTitle, ERROR_MESSAGE);
                    return;
                }
            if (!firstName.trim().matches("[\\p{L} '\\-]+")) {
                JOptionPane.showMessageDialog(this, "First name can only contain letters, spaces, hyphens, and apostrophes", errorTitle, ERROR_MESSAGE);
                    return;
                }

            //Validate last name
            if (lastName == null || lastName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please provide your last name", errorTitle, ERROR_MESSAGE);
                    return;
                }
            if (!lastName.trim().matches("[\\p{L} '\\-]+")) {
                JOptionPane.showMessageDialog(this, "Last name can only contain letters, spaces, hyphens, and apostrophes", errorTitle, ERROR_MESSAGE);
                    return;
                }
            
            //Validate age
            if (age <18) {
                JOptionPane.showMessageDialog(this, "Please select a valid date of birth. Must be 18 or older", errorTitle, ERROR_MESSAGE);
                return;
            }

            //Validate gender
            if (gender == null || gender.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please check an option to indicate your gender", errorTitle, ERROR_MESSAGE);
                return;
            }

            //Validate phone
            if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Invalid phone number format. \nPlease use the following format: 123-456-7890", errorTitle, ERROR_MESSAGE);
                return;
            }

            //Validate email
            if (email == null || email.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please provide your email", errorTitle, ERROR_MESSAGE);
                return;
            }
            
            if (!email.trim().matches("^[\\w.+-]+@[\\w-]+(\\.[\\w-]+)+$")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid email address, for example name@example.com", errorTitle, ERROR_MESSAGE);
                return;
            }

            //Validate continent
            if (continent == null || continent.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select an option in the continent field", errorTitle, ERROR_MESSAGE);
                return;
            }
            
            //Validate hobbies
            if (hobbies == null || hobbies.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please select an option in the hobbies field", errorTitle, ERROR_MESSAGE);
                return;
            }
            
            //Validate photo
            if (photoPath == null || photoPath.trim().isEmpty()
                || new ImageIcon(photoPath).getIconWidth() <= 0) {
            JOptionPane.showMessageDialog(this, "Please upload a valid image file", errorTitle, ERROR_MESSAGE);
            return;
            }

            User user1 = new User();
            user1.setFirstName(firstName);
            user1.setLastName(lastName);
            user1.setGender(gender);
            user1.setDateOfBirth(dateOfBirth);
            user1.setAge(age);
            user1.setPhone(phone);
            user1.setEmail(email);
            user1.setContinent(continent);
            user1.setExperience(experience);
            user1.setHobbies(hobbies);
            user1.setPhotoPath(photoPath);

            String successMessage = "First Name: " + firstName.trim()
            + "\nLast Name: " + lastName.trim()
            + "\nDate of Birth (yyyy-mm-dd): " + dateOfBirth
            + "\nAge: " + age
            + "\nGender: " + gender
            + "\nPhone: " + phone
            + "\nEmail: " + email
            + "\nContinent: " + continent
            + "\nExperience: " + (experience == null || experience.trim().isEmpty() ? "None" : experience)
            + "\nHobbies: " + (hobbies == null || hobbies.trim().isEmpty() ? "None" : hobbies)
            + "\nPhoto Path: " + (photoPath == null || photoPath.trim().isEmpty() ? "Not uploaded" : photoPath);

            //Build the photo icon (if one was uploaded)
            ImageIcon photoIcon = null;
            if (photoPath != null && !photoPath.trim().isEmpty()) {
                ImageIcon rawIcon = new ImageIcon(photoPath);
                Image scaled = rawIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                photoIcon = new ImageIcon(scaled);
            }

            JOptionPane.showMessageDialog(
                this,
                successMessage,
                "Success",
                JOptionPane.INFORMATION_MESSAGE,
                photoIcon
            );
            
            if (viewPanel != null && cardContainer != null) {
                viewPanel.displayUser(user1);
                CardLayout cl = (CardLayout) cardContainer.getLayout();
                cl.show(cardContainer, "view");
                cardContainer.revalidate();
                cardContainer.repaint();
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Age Provided", errorTitle, ERROR_MESSAGE);
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed

    }//GEN-LAST:event_emailTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel1;
    private javax.swing.JLabel asterisk1;
    private javax.swing.JLabel asterisk11;
    private javax.swing.JLabel asterisk2;
    private javax.swing.JLabel asterisk3;
    private javax.swing.JLabel asterisk4;
    private javax.swing.JLabel asterisk5;
    private javax.swing.JLabel asterisk6;
    private javax.swing.JLabel asterisk7;
    private javax.swing.JLabel asterisk8;
    private javax.swing.JLabel asterisk9;
    private javax.swing.JComboBox<String> continentCombo;
    private javax.swing.JLabel continentLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JLabel experienceLabel1;
    private javax.swing.JTextArea experienceTextArea;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextArea hobbiesTextArea;
    private de.wannawork.jcalendar.JCalendarComboBox jCalendarCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JLabel requiredFieldLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables

    // Phone field placeholder
    private javax.swing.text.MaskFormatter createPhoneMask() {
        javax.swing.text.MaskFormatter mask = null;
        try {
            mask = new javax.swing.text.MaskFormatter("###-###-####");
            mask.setPlaceholderCharacter(' ');
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        return mask;
    }
}
